"""new table added for keeong hardware prodc=uct categories

Revision ID: 00cb70d4ec70
Revises: c56e4abd2bdb
Create Date: 2024-12-27 16:08:58.215466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cb70d4ec70'
down_revision: Union[str, None] = 'c56e4abd2bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_product_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('search_keywords', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('opening_hardware_materials', sa.Column('hardware_product_category_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'opening_hardware_materials', 'hardware_product_category', ['hardware_product_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opening_hardware_materials', type_='foreignkey')
    op.drop_column('opening_hardware_materials', 'hardware_product_category_id')
    op.drop_table('hardware_product_category')
    # ### end Alembic commands ###
