"""is_disabled flag added in the adon_opening_fileds table

Revision ID: 025606873a01
Revises: ff96356b4688
Create Date: 2025-01-09 17:30:14.687000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025606873a01'
down_revision: Union[str, None] = 'ff96356b4688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adon_opening_fields', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adon_opening_fields', 'is_disabled')
    # ### end Alembic commands ###
