"""Add has_door_requested ,has_frame_requested, has_hw_requested in schedules

Revision ID: 061f2efcdbab
Revises: 4094b7f66016
Create Date: 2026-03-30 14:17:25.352175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061f2efcdbab'
down_revision: Union[str, None] = '4094b7f66016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('has_door_requested', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('has_frame_requested', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('has_hw_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'has_hw_requested')
    op.drop_column('schedules', 'has_frame_requested')
    op.drop_column('schedules', 'has_door_requested')
    # ### end Alembic commands ###
