"""assign hardware to opening schedule opening related changes

Revision ID: 066d7840d6c0
Revises: 7c8fc97473fd
Create Date: 2024-12-26 13:07:12.464119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '066d7840d6c0'
down_revision: Union[str, None] = '7c8fc97473fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_data_ibfk_4', 'schedule_data', type_='foreignkey')
    op.drop_column('schedule_data', 'opening_hardware_material_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('opening_hardware_material_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('schedule_data_ibfk_4', 'schedule_data', 'opening_hardware_materials', ['opening_hardware_material_id'], ['id'])
    # ### end Alembic commands ###
