"""Add schedule_installation_mapping_component_data table

Revision ID: 0695c93c96a0
Revises: b86ea17973e0
Create Date: 2025-06-05 19:48:37.859504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0695c93c96a0'
down_revision: Union[str, None] = 'b86ea17973e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_installation_mapping_component_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_installation_mapping_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_opening_hardware_material_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FAILED', 'SUCCESS', name='status'), nullable=True),
    sa.Column('component', sa.Enum('HARDWARE', 'FRAME', 'DOOR', name='component'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_id'], ['schedule_installation_mapping.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_opening_hardware_material_id'], ['schedule_opening_hardware_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('id', table_name='schedule_installation_mapping_prep_data')
    op.drop_table('schedule_installation_mapping_prep_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_installation_mapping_prep_data',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('schedule_installation_mapping_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('schedule_data_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'IN_PROGRESS', 'FAILED', 'SUCCESS'), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_data_id'], ['schedule_data.id'], name='schedule_installation_mapping_prep_data_ibfk_1'),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_id'], ['schedule_installation_mapping.id'], name='schedule_installation_mapping_prep_data_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'schedule_installation_mapping_prep_data', ['id'], unique=True)
    op.drop_table('schedule_installation_mapping_component_data')
    # ### end Alembic commands ###
