"""Added change_order,co_schedules,work_order,wo_assignee,co_change_stats and wo_schedules tables

Revision ID: 095af611f59e
Revises: eb0ed4719cfd
Create Date: 2025-07-11 14:01:51.473488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095af611f59e'
down_revision: Union[str, None] = 'eb0ed4719cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED', name='changeorderstatusenum'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_no', sa.String(length=100), nullable=True),
    sa.Column('wo_number', sa.String(length=100), nullable=True),
    sa.Column('wo_date', sa.DateTime(), nullable=True),
    sa.Column('wo_status', sa.Enum('PENDING', 'DISPATCHED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='workorderstatusenum'), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('site_address', sa.String(length=255), nullable=True),
    sa.Column('site_city', sa.String(length=100), nullable=True),
    sa.Column('bill_to_name', sa.String(length=255), nullable=True),
    sa.Column('cutomer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_contact_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_fax', sa.String(length=50), nullable=True),
    sa.Column('customer_po', sa.String(length=100), nullable=True),
    sa.Column('job_number', sa.String(length=100), nullable=True),
    sa.Column('job_desc', sa.String(length=255), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=True),
    sa.Column('dispatched_date', sa.DateTime(), nullable=True),
    sa.Column('dispatcher', sa.String(length=100), nullable=True),
    sa.Column('work_requested', sa.Text(), nullable=True),
    sa.Column('dispatch_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_table('co_change_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('schedule_id', sa.String(length=32), nullable=True),
    sa.Column('opening_number', sa.String(length=100), nullable=True),
    sa.Column('component', sa.Enum('MULTIPLIER', 'PERCENTAGE', name='cochangestatscomponentenum'), nullable=True),
    sa.Column('short_code', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('curr_schedule_feature_code', sa.String(length=255), nullable=True),
    sa.Column('co_schedule_feature_code', sa.String(length=255), nullable=True),
    sa.Column('curr_schedule_option_code', sa.String(length=255), nullable=True),
    sa.Column('co_schedule_option_code', sa.String(length=255), nullable=True),
    sa.Column('curr_schedule_value', sa.String(length=255), nullable=True),
    sa.Column('co_schedule_value', sa.String(length=255), nullable=True),
    sa.Column('curr_schedule_total_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_total_base_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_total_sell_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_quantity', sa.Float(), nullable=True),
    sa.Column('curr_schedule_final_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_final_base_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_final_sell_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_discount', sa.Float(), nullable=True),
    sa.Column('curr_schedule_discount_type', sa.Enum('MULTIPLIER', 'PERCENTAGE', name='projectmaterialsdiscounttypeenum'), nullable=True),
    sa.Column('curr_schedule_surcharge', sa.Float(), nullable=True),
    sa.Column('curr_schedule_surcharge_type', sa.Enum('MULTIPLIER', 'PERCENTAGE', name='projectmaterialssurchargetypeenum'), nullable=True),
    sa.Column('curr_schedule_margin', sa.Float(), nullable=True),
    sa.Column('curr_schedule_markup', sa.Float(), nullable=True),
    sa.Column('co_schedule_total_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_total_base_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_total_sell_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_quantity', sa.Float(), nullable=True),
    sa.Column('co_schedule_final_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_final_base_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_final_sell_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('co_schedule_discount', sa.Float(), nullable=True),
    sa.Column('co_schedule_discount_type', sa.Enum('MULTIPLIER', 'PERCENTAGE', name='projectmaterialsdiscounttypeenum'), nullable=True),
    sa.Column('co_schedule_surcharge', sa.Float(), nullable=True),
    sa.Column('co_schedule_surcharge_type', sa.Enum('MULTIPLIER', 'PERCENTAGE', name='projectmaterialssurchargetypeenum'), nullable=True),
    sa.Column('co_schedule_margin', sa.Float(), nullable=True),
    sa.Column('co_schedule_markup', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('is_adon_field', sa.Boolean(), nullable=True),
    sa.Column('has_price_dependancy', sa.Boolean(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('co_id', sa.String(length=32), nullable=True),
    sa.Column('schedule_id', sa.String(length=32), nullable=True),
    sa.Column('frame_section_file_path', sa.Text(), nullable=True),
    sa.Column('frame_section_file_type', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('installation_amount', sa.Float(), nullable=True),
    sa.Column('take_off_data', sa.JSON(), nullable=True),
    sa.Column('take_off_hardware_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['change_order.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wo_assignee',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wo_id', sa.String(length=32), nullable=True),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wo_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wo_id', sa.String(length=32), nullable=True),
    sa.Column('schedule_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schedule_installation_mapping', sa.Column('wo_schedule_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'schedule_installation_mapping', 'wo_schedules', ['wo_schedule_id'], ['id'])
    op.add_column('schedules', sa.Column('is_freezed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'is_freezed')
    op.drop_constraint(None, 'schedule_installation_mapping', type_='foreignkey')
    op.drop_column('schedule_installation_mapping', 'wo_schedule_id')
    op.drop_table('wo_schedules')
    op.drop_table('wo_assignee')
    op.drop_table('co_schedules')
    op.drop_table('co_change_stats')
    op.drop_table('work_order')
    op.drop_table('change_order')
    # ### end Alembic commands ###
