"""change in schedule model

Revision ID: 12228b7bf12d
Revises: 6f7c12bfe0e7
Create Date: 2024-12-12 17:28:03.532238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12228b7bf12d'
down_revision: Union[str, None] = '6f7c12bfe0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('door_qty', sa.Float(), nullable=True))
    op.drop_constraint('schedules_ibfk_1', 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'door_qy')
    op.drop_column('schedules', 'project_raw_material_id')
    op.drop_column('schedules', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('quantity', mysql.FLOAT(), nullable=True))
    op.add_column('schedules', sa.Column('project_raw_material_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('schedules', sa.Column('door_qy', mysql.FLOAT(), nullable=True))
    op.create_foreign_key('schedules_ibfk_1', 'schedules', 'project_raw_materials', ['project_raw_material_id'], ['id'])
    op.drop_column('schedules', 'door_qty')
    # ### end Alembic commands ###
