"""order items with activate po relationship migration

Revision ID: 13fcedbb0819
Revises: 69e31f775bad
Create Date: 2025-02-19 13:07:24.741155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fcedbb0819'
down_revision: Union[str, None] = '69e31f775bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('active_po_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'ordered_items', 'active_po', ['active_po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordered_items', type_='foreignkey')
    op.drop_column('ordered_items', 'active_po_id')
    # ### end Alembic commands ###
