"""relation correction with ScheduleInstallationMappingComponentData table

Revision ID: 1b3774c61799
Revises: 0695c93c96a0
Create Date: 2025-06-05 21:08:55.221945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3774c61799'
down_revision: Union[str, None] = '0695c93c96a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
