"""adding installation amount field to schedues table

Revision ID: 1bbb508bc019
Revises: 882d41539d2d
Create Date: 2025-05-29 15:43:39.879748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbb508bc019'
down_revision: Union[str, None] = '882d41539d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('installation_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'installation_amount')
    # ### end Alembic commands ###
