"""add is_opening_data flag in the adon_opening_fields

Revision ID: 1d0a80113120
Revises: 8183a34af589
Create Date: 2024-12-17 13:40:21.347171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0a80113120'
down_revision: Union[str, None] = '8183a34af589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adon_opening_fields', sa.Column('is_opening_data', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('door_material_code', sa.String(length=100), nullable=True))
    op.add_column('schedules', sa.Column('frame_material_code', sa.String(length=100), nullable=True))
    op.add_column('schedules', sa.Column('extra_attributes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'extra_attributes')
    op.drop_column('schedules', 'frame_material_code')
    op.drop_column('schedules', 'door_material_code')
    op.drop_column('adon_opening_fields', 'is_opening_data')
    # ### end Alembic commands ###
