"""added part_numebr in the OpeningChangeStats

Revision ID: 2743e9e26830
Revises: 8a3dc8139db5
Create Date: 2025-04-23 13:49:27.055481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2743e9e26830'
down_revision: Union[str, None] = '8a3dc8139db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opening_change_stats', sa.Column('part_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opening_change_stats', 'part_number')
    # ### end Alembic commands ###
