"""changes regarding new location fields added for geo tracking in installer app

Revision ID: 3431b9d185e8
Revises: e4206057f397
Create Date: 2026-01-28 22:47:06.239957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3431b9d185e8'
down_revision: Union[str, None] = 'e4206057f397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wo_assignee', sa.Column('location_details', sa.JSON(), nullable=True))
    op.add_column('work_order', sa.Column('site_location', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order', 'site_location')
    op.drop_column('wo_assignee', 'location_details')
    # ### end Alembic commands ###
