"""added table ordered_item_docs for storing order related docs

Revision ID: 3590b7e52ddf
Revises: 6961073865b3
Create Date: 2025-03-12 10:33:25.204233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3590b7e52ddf'
down_revision: Union[str, None] = '6961073865b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordered_item_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['ordered_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered_item_docs')
    # ### end Alembic commands ###
