"""Added has_applied column and removed PARTIALLY_APPROVED enum in change order table

Revision ID: 385c67b1d72e
Revises: 7320c0bce96b
Create Date: 2025-09-17 13:13:15.082676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385c67b1d72e'
down_revision: Union[str, None] = '7320c0bce96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_order', sa.Column('has_applied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_order', 'has_applied')
    # ### end Alembic commands ###
