"""Add expected_delivery_days to ordered_items

Revision ID: 39b55f4297f6
Revises: 531e44fe4c3c
Create Date: 2025-03-05 12:20:22.392533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b55f4297f6'
down_revision: Union[str, None] = '531e44fe4c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('expected_delivery_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'expected_delivery_days')
    # ### end Alembic commands ###
