"""removed 'po_name' from active_po and respective project files

Revision ID: 39d84ed36e2a
Revises: 7f57e351381a
Create Date: 2025-03-27 13:05:01.615325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39d84ed36e2a'
down_revision: Union[str, None] = '7f57e351381a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_po', 'po_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('po_name', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
