"""adding is basic discunt flag added to opening hardware materials table

Revision ID: 3bbe76597768
Revises: d5961b497893
Create Date: 2025-05-08 18:17:04.871710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbe76597768'
down_revision: Union[str, None] = 'd5961b497893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opening_hardware_materials', sa.Column('is_basic_discount', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opening_hardware_materials', 'is_basic_discount')
    # ### end Alembic commands ###
