"""Added change_order_docs and change_order_status_logs table

Revision ID: 3d7bf6cdcff5
Revises: 7a558dfe6ddc
Create Date: 2025-09-04 18:27:51.974398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7bf6cdcff5'
down_revision: Union[str, None] = '7a558dfe6ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_order_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('co_id', sa.String(length=36), nullable=True),
    sa.Column('doc_type', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['change_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_order_status_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED', name='changeorderstatusenum'), nullable=True),
    sa.Column('co_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['change_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_order_status_logs')
    op.drop_table('change_order_docs')
    # ### end Alembic commands ###
