"""Increase member_id column size to 36

Revision ID: 3fc4be99841d
Revises: 14724cc50b6e
Create Date: 2025-07-11 16:05:11.385544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fc4be99841d'
down_revision: Union[str, None] = '14724cc50b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wo_assignee', 'member_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wo_assignee', 'member_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
