"""add schedule master data field at opening_door_frame_materials table

Revision ID: 4094b7f66016
Revises: 3431b9d185e8
Create Date: 2026-02-27 22:56:31.409126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4094b7f66016'
down_revision: Union[str, None] = '3431b9d185e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_door_frame_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('short_code', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('raw_material_code', sa.String(length=20), nullable=True),
    sa.Column('material_type', sa.Enum('FRAME', 'DOOR', 'OTHER', name='material_type'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('base_feature', sa.JSON(), nullable=True),
    sa.Column('base_price', sa.JSON(), nullable=True),
    sa.Column('adon_feature', sa.JSON(), nullable=True),
    sa.Column('adon_price', sa.JSON(), nullable=True),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('content_file_path', sa.Text(), nullable=True),
    sa.Column('content_file_name', sa.Text(), nullable=True),
    sa.Column('content_file_type', sa.String(length=36), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('is_basic_discount', sa.Boolean(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='discount_type'), nullable=True),
    sa.Column('surcharge', sa.Float(), nullable=True),
    sa.Column('surcharge_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='surcharge_type'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('schedule_master_data', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule_opening_door_frame_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('material_type', sa.Enum('FRAME', 'DOOR', 'OTHER', name='material_type'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('latest_data', sa.Boolean(), nullable=True),
    sa.Column('has_ordered', sa.Boolean(), nullable=True),
    sa.Column('has_shipped', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=250), nullable=True),
    sa.Column('opening_door_frame_material_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['opening_door_frame_material_id'], ['opening_door_frame_materials.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_opening_door_frame_materials')
    op.drop_table('opening_door_frame_materials')
    # ### end Alembic commands ###
