"""shipping related dates added

Revision ID: 43864b3c938c
Revises: 6b1c95c180a0
Create Date: 2025-03-20 12:47:25.748674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43864b3c938c'
down_revision: Union[str, None] = '6b1c95c180a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('shipping_initiate_date', sa.Date(), nullable=True))
    op.add_column('ordered_items', sa.Column('shipped_date', sa.Date(), nullable=True))
    op.add_column('ordered_items', sa.Column('estimated_fulfillment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'estimated_fulfillment_date')
    op.drop_column('ordered_items', 'shipped_date')
    op.drop_column('ordered_items', 'shipping_initiate_date')
    # ### end Alembic commands ###
