"""Added the WoAssigneeTimeLog model

Revision ID: 45894b37f03e
Revises: 9fa7f2dbc8e5
Create Date: 2025-08-06 11:18:24.972607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45894b37f03e'
down_revision: Union[str, None] = '9fa7f2dbc8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wo_assignee_time_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wo_assignee_id', sa.String(length=36), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['wo_assignee_id'], ['wo_assignee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wo_assignee_time_log')
    # ### end Alembic commands ###
