"""Take-off-sheet opening required information: location_1, from_to, location_2

Revision ID: 46b63e21a802
Revises: 39d84ed36e2a
Create Date: 2025-04-15 17:48:06.447138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46b63e21a802'
down_revision: Union[str, None] = '39d84ed36e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_take_off_sheet_section_area_items', sa.Column('location_1', sa.String(length=250), nullable=True))
    op.add_column('project_take_off_sheet_section_area_items', sa.Column('location_2', sa.String(length=250), nullable=True))
    op.add_column('project_take_off_sheet_section_area_items', sa.Column('from_to', sa.String(length=250), nullable=True))
    op.drop_column('project_take_off_sheet_section_area_items', 'to_location')
    op.drop_column('project_take_off_sheet_section_area_items', 'from_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_take_off_sheet_section_area_items', sa.Column('from_location', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('project_take_off_sheet_section_area_items', sa.Column('to_location', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('project_take_off_sheet_section_area_items', 'from_to')
    op.drop_column('project_take_off_sheet_section_area_items', 'location_2')
    op.drop_column('project_take_off_sheet_section_area_items', 'location_1')
    # ### end Alembic commands ###
