"""removed is_shipped flag from ActivePo table

Revision ID: 49ba7d1f7bc3
Revises: b9d45571c1f3
Create Date: 2025-03-12 20:04:11.341897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49ba7d1f7bc3'
down_revision: Union[str, None] = 'b9d45571c1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_po', 'is_shipped')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('is_shipped', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
