"""adding shippent done flag fields to schedue_data table

Revision ID: 4ceeef349502
Revises: 7092473e0be7
Create Date: 2025-09-23 11:30:06.259095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceeef349502'
down_revision: Union[str, None] = '7092473e0be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('has_shipped', sa.Boolean(), nullable=True))
    op.execute("UPDATE schedule_data SET has_shipped = FALSE WHERE has_shipped IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_data', 'has_shipped')
    # ### end Alembic commands ###
