"""orderd_data to ordered_date

Revision ID: 530789b95ed1
Revises: 3f75b0fe9329
Create Date: 2025-02-20 11:13:05.255730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530789b95ed1'
down_revision: Union[str, None] = '3f75b0fe9329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('ordered_date', sa.Date(), nullable=True))
    op.drop_column('active_po', 'orderd_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('orderd_date', sa.DATE(), nullable=True))
    op.drop_column('active_po', 'ordered_date')
    # ### end Alembic commands ###
