"""field added part_number to order_items table

Revision ID: 531e44fe4c3c
Revises: 530789b95ed1
Create Date: 2025-02-26 18:43:00.822538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531e44fe4c3c'
down_revision: Union[str, None] = '530789b95ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('part_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'part_number')
    # ### end Alembic commands ###
