"""Removed take_off_data and take_off_hardware_data fields in co_schedules table

Revision ID: 5c3584a16a02
Revises: 7595917f2d39
Create Date: 2025-09-08 15:10:32.407501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c3584a16a02'
down_revision: Union[str, None] = '7595917f2d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_schedules', 'take_off_hardware_data')
    op.drop_column('co_schedules', 'take_off_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_schedules', sa.Column('take_off_data', mysql.JSON(), nullable=True))
    op.add_column('co_schedules', sa.Column('take_off_hardware_data', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
