"""remove parent id

Revision ID: 5d1efccc0c1e
Revises: 7d12abfc6ade
Create Date: 2025-01-07 18:34:01.695581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d1efccc0c1e'
down_revision: Union[str, None] = '7d12abfc6ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardware_product_category', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_product_category', sa.Column('parent_id', mysql.VARCHAR(length=36), nullable=True))
    # ### end Alembic commands ###
