"""migration on schedule table

Revision ID: 5f1443c9448f
Revises: bf950fb381ef
Create Date: 2024-12-26 13:52:09.120513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f1443c9448f'
down_revision: Union[str, None] = 'bf950fb381ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('location_1', sa.String(length=250), nullable=True))
    op.add_column('schedules', sa.Column('location_2', sa.String(length=250), nullable=True))
    op.add_column('schedules', sa.Column('from_to', sa.String(length=250), nullable=True))
    op.drop_column('schedules', 'swing_to')
    op.drop_column('schedules', 'open_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('open_from', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('schedules', sa.Column('swing_to', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('schedules', 'from_to')
    op.drop_column('schedules', 'location_2')
    op.drop_column('schedules', 'location_1')
    # ### end Alembic commands ###
