"""added the relation take_off_hardware_product_catagory_materials

Revision ID: 6235deca8f12
Revises: 46b63e21a802
Create Date: 2025-04-17 19:13:54.312261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6235deca8f12'
down_revision: Union[str, None] = '46b63e21a802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_materials', sa.Column('hardware_product_category_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'project_materials', 'hardware_product_category', ['hardware_product_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_materials', type_='foreignkey')
    op.drop_column('project_materials', 'hardware_product_category_id')
    # ### end Alembic commands ###
