"""praent id added to hw product category table

Revision ID: 6271cdc4e3bf
Revises: 00cb70d4ec70
Create Date: 2024-12-27 19:15:12.490046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6271cdc4e3bf'
down_revision: Union[str, None] = '00cb70d4ec70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_product_category', sa.Column('parent_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardware_product_category', 'parent_id')
    # ### end Alembic commands ###
