"""adding margin in schedule data table

Revision ID: 6551d9d00d9c
Revises: f44b2ff7e924
Create Date: 2025-04-24 20:29:48.609342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6551d9d00d9c'
down_revision: Union[str, None] = 'f44b2ff7e924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
