"""opening schedule rated chaneg in db model

Revision ID: 65708b61f26b
Revises: 86c69c2170f1
Create Date: 2024-12-09 17:06:12.211079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65708b61f26b'
down_revision: Union[str, None] = '86c69c2170f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
