"""make material type nullable

Revision ID: 661067fe132f
Revises: cdc357027351
Create Date: 2026-04-17 17:57:57.944893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '661067fe132f'
down_revision: Union[str, None] = 'cdc357027351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('door_frame_raw_material_sections', 'material_type',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('door_frame_raw_material_sections', 'material_type',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
