"""Added the has_ordered,version and latest_data column in schedule_data table

Revision ID: 665697dd8f7d
Revises: d1c67093f314
Create Date: 2025-09-19 13:00:40.201159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665697dd8f7d'
down_revision: Union[str, None] = 'd1c67093f314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_opening_hardware_materials', sa.Column('latest_data', sa.Boolean(), nullable=True))
    op.add_column('schedule_opening_hardware_materials', sa.Column('has_ordered', sa.Boolean(), nullable=True))
    op.add_column('schedule_opening_hardware_materials', sa.Column('version', sa.String(length=250), nullable=True))
    # Set default values for old records
    op.execute("UPDATE schedule_opening_hardware_materials SET latest_data = TRUE, has_ordered = FALSE, version = 'v0' WHERE latest_data IS NULL AND has_ordered IS NULL AND version IS NULL;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_opening_hardware_materials', 'version')
    op.drop_column('schedule_opening_hardware_materials', 'has_ordered')
    op.drop_column('schedule_opening_hardware_materials', 'latest_data')
    # ### end Alembic commands ###
