"""added receiving, missing, damaged flag with labbled photo

Revision ID: 6961073865b3
Revises: 39b55f4297f6
Create Date: 2025-03-07 16:52:05.991266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6961073865b3'
down_revision: Union[str, None] = '39b55f4297f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('is_received', sa.Boolean(), nullable=True))
    op.add_column('ordered_items', sa.Column('is_missing', sa.Boolean(), nullable=True))
    op.add_column('ordered_items', sa.Column('is_damaged', sa.Boolean(), nullable=True))
    op.add_column('ordered_items', sa.Column('generated_shipping_label_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'generated_shipping_label_path')
    op.drop_column('ordered_items', 'is_damaged')
    op.drop_column('ordered_items', 'is_missing')
    op.drop_column('ordered_items', 'is_received')
    # ### end Alembic commands ###
