"""active po migration

Revision ID: 69e31f775bad
Revises: edf4cf9622a0
Create Date: 2025-02-19 13:05:25.217862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e31f775bad'
down_revision: Union[str, None] = 'edf4cf9622a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_po',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('sold_to', sa.Text(), nullable=True),
    sa.Column('ship_to', sa.Text(), nullable=True),
    sa.Column('po_name', sa.String(length=255), nullable=True),
    sa.Column('order_contact', sa.String(length=255), nullable=True),
    sa.Column('date_required', sa.Date(), nullable=True),
    sa.Column('date_ordered', sa.Date(), nullable=True),
    sa.Column('order_contact_email', sa.String(length=255), nullable=True),
    sa.Column('delivery_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('purchase_order', sa.String(length=255), nullable=True),
    sa.Column('orderd_date', sa.DateTime(), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('quote', sa.String(length=255), nullable=True),
    sa.Column('scheduled_ship_date', sa.Date(), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('po_acknowledgement', sa.String(length=255), nullable=True),
    sa.Column('ship_via', sa.String(length=255), nullable=True),
    sa.Column('ship_instructions', sa.Text(), nullable=True),
    sa.Column('order_type', sa.String(length=255), nullable=True),
    sa.Column('order_type_description', sa.Text(), nullable=True),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('service_center', sa.String(length=255), nullable=True),
    sa.Column('transfer_point_ship_via', sa.String(length=255), nullable=True),
    sa.Column('transfer_point_carrier', sa.String(length=255), nullable=True),
    sa.Column('bundling_code', sa.String(length=50), nullable=True),
    sa.Column('prepaid_collect_code_id', sa.Integer(), nullable=True),
    sa.Column('is_job_site', sa.Boolean(), nullable=True),
    sa.Column('ordered_item_quantity', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_po')
    # ### end Alembic commands ###
