"""removed date_ordered

Revision ID: 6b1c95c180a0
Revises: d01847732524
Create Date: 2025-03-19 11:11:40.812405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1c95c180a0'
down_revision: Union[str, None] = 'd01847732524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_po', 'date_ordered')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('date_ordered', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
