"""add part number in schedule_opening_door_frame_materials

Revision ID: 6be578731c20
Revises: 061f2efcdbab
Create Date: 2026-04-01 00:05:46.642438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be578731c20'
down_revision: Union[str, None] = '061f2efcdbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_opening_door_frame_materials', sa.Column('part_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_opening_door_frame_materials', 'part_number')
    # ### end Alembic commands ###
