"""opening schedule related table changes in schedule data and schedules and adon fields

Revision ID: 6f7c12bfe0e7
Revises: 65708b61f26b
Create Date: 2024-12-12 13:36:26.239806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7c12bfe0e7'
down_revision: Union[str, None] = '65708b61f26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adon_opening_fields', sa.Column('is_adon_field', sa.Boolean(), nullable=True))
    op.add_column('schedule_data', sa.Column('is_manual', sa.Boolean(), nullable=True))
    op.add_column('schedule_data', sa.Column('is_table_data', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('area', sa.String(length=250), nullable=True))
    op.add_column('schedules', sa.Column('open_from', sa.String(length=250), nullable=True))
    op.add_column('schedules', sa.Column('swing_to', sa.String(length=250), nullable=True))
    op.add_column('schedules', sa.Column('door_qy', sa.Float(), nullable=True))
    op.add_column('schedules', sa.Column('frame_qty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'frame_qty')
    op.drop_column('schedules', 'door_qy')
    op.drop_column('schedules', 'swing_to')
    op.drop_column('schedules', 'open_from')
    op.drop_column('schedules', 'area')
    op.drop_column('schedule_data', 'is_table_data')
    op.drop_column('schedule_data', 'is_manual')
    op.drop_column('adon_opening_fields', 'is_adon_field')
    # ### end Alembic commands ###
