"""opening hardware material related refactor

Revision ID: 7078296360e8
Revises: 860e5bbf3e92
Create Date: 2024-12-20 13:13:18.579715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7078296360e8'
down_revision: Union[str, None] = '860e5bbf3e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='opening_hardware_group_materials')
    op.drop_constraint('schedule_data_ibfk_4', 'schedule_data', type_='foreignkey')
    op.drop_table('opening_hardware_group_materials')
    op.drop_index('id', table_name='opening_hardware_groups')
    op.drop_table('opening_hardware_groups')
    op.add_column('adon_opening_field_options', sa.Column('search_keywords', sa.Text(), nullable=True))
    op.add_column('adon_opening_fields', sa.Column('search_keywords', sa.Text(), nullable=True))
    op.add_column('opening_hardware_materials', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('opening_hardware_materials', sa.Column('final_amount', sa.Float(), nullable=True))
    op.add_column('opening_hardware_materials', sa.Column('final_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_hardware_materials', sa.Column('final_base_amount', sa.Float(), nullable=True))
    op.add_column('opening_hardware_materials', sa.Column('final_extended_sell_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'opening_hardware_materials', 'projects', ['project_id'], ['id'])
    op.drop_column('opening_hardware_materials', 'discount_is_basic')
    op.add_column('schedule_data', sa.Column('feature_data', sa.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('price_data', sa.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('opening_hardware_material_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'schedule_data', 'opening_hardware_materials', ['opening_hardware_material_id'], ['id'])
    op.drop_column('schedule_data', 'opening_hardware_group_material_id')
    op.drop_column('schedule_data', 'adon_feature_code')
    op.drop_column('schedule_data', 'adon_price')
    op.drop_column('schedule_data', 'adon_option_code')
    op.drop_column('schedule_data', 'adon_feature')
    op.drop_column('schedule_data', 'base_feature')
    op.drop_column('schedule_data', 'base_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('base_price', mysql.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('base_feature', mysql.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('adon_feature', mysql.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('adon_option_code', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('schedule_data', sa.Column('adon_price', mysql.JSON(), nullable=True))
    op.add_column('schedule_data', sa.Column('adon_feature_code', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('schedule_data', sa.Column('opening_hardware_group_material_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'schedule_data', type_='foreignkey')
    op.create_foreign_key('schedule_data_ibfk_4', 'schedule_data', 'opening_hardware_group_materials', ['opening_hardware_group_material_id'], ['id'])
    op.drop_column('schedule_data', 'opening_hardware_material_id')
    op.drop_column('schedule_data', 'additional_data')
    op.drop_column('schedule_data', 'price_data')
    op.drop_column('schedule_data', 'feature_data')
    op.add_column('opening_hardware_materials', sa.Column('discount_is_basic', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opening_hardware_materials', type_='foreignkey')
    op.drop_column('opening_hardware_materials', 'final_extended_sell_amount')
    op.drop_column('opening_hardware_materials', 'final_base_amount')
    op.drop_column('opening_hardware_materials', 'final_sell_amount')
    op.drop_column('opening_hardware_materials', 'final_amount')
    op.drop_column('opening_hardware_materials', 'quantity')
    op.drop_column('adon_opening_fields', 'search_keywords')
    op.drop_column('adon_opening_field_options', 'search_keywords')
    op.create_table('opening_hardware_groups',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_count', mysql.FLOAT(), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_base_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_extended_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('project_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='opening_hardware_groups_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'opening_hardware_groups', ['id'], unique=True)
    op.create_table('opening_hardware_group_materials',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_base_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_extended_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('final_amount', mysql.FLOAT(), nullable=True),
    sa.Column('final_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('final_base_amount', mysql.FLOAT(), nullable=True),
    sa.Column('final_extended_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('opening_hardware_material_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('opening_hardware_group_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['opening_hardware_group_id'], ['opening_hardware_groups.id'], name='opening_hardware_group_materials_ibfk_1'),
    sa.ForeignKeyConstraint(['opening_hardware_material_id'], ['opening_hardware_materials.id'], name='opening_hardware_group_materials_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'opening_hardware_group_materials', ['id'], unique=True)
    # ### end Alembic commands ###
