"""adding shippent done flag fields to schedues table

Revision ID: 7092473e0be7
Revises: 665697dd8f7d
Create Date: 2025-09-22 23:23:59.311286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7092473e0be7'
down_revision: Union[str, None] = '665697dd8f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('has_door_shipped', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('has_frame_shipped', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('has_hw_shipped', sa.Boolean(), nullable=True))
    op.execute("UPDATE schedules SET has_door_shipped = FALSE, has_frame_shipped = FALSE, has_hw_shipped = FALSE WHERE has_door_shipped IS NULL AND has_frame_shipped IS NULL AND has_hw_shipped IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'has_hw_shipped')
    op.drop_column('schedules', 'has_frame_shipped')
    op.drop_column('schedules', 'has_door_shipped')
    # ### end Alembic commands ###
