"""Added has_door_ordered,has_frame_ordered and has_hw_ordered in schedules

Revision ID: 7320c0bce96b
Revises: c2df2ec77d82
Create Date: 2025-09-16 17:13:25.200370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7320c0bce96b'
down_revision: Union[str, None] = 'c2df2ec77d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('has_door_ordered', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('has_frame_ordered', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('has_hw_ordered', sa.Boolean(), nullable=True))
    op.execute("UPDATE schedules SET has_door_ordered = FALSE, has_frame_ordered = FALSE, has_hw_ordered = FALSE WHERE has_door_ordered IS NULL AND has_frame_ordered IS NULL AND has_hw_ordered IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'has_hw_ordered')
    op.drop_column('schedules', 'has_frame_ordered')
    op.drop_column('schedules', 'has_door_ordered')
    # ### end Alembic commands ###
