"""Added the extra fields in co_schedules table

Revision ID: 7595917f2d39
Revises: abb8af4590e4
Create Date: 2025-09-08 14:53:00.950710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7595917f2d39'
down_revision: Union[str, None] = 'abb8af4590e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_schedules', sa.Column('area', sa.String(length=250), nullable=True))
    op.add_column('co_schedules', sa.Column('location_1', sa.String(length=250), nullable=True))
    op.add_column('co_schedules', sa.Column('from_to', sa.String(length=250), nullable=True))
    op.add_column('co_schedules', sa.Column('location_2', sa.String(length=250), nullable=True))
    op.add_column('co_schedules', sa.Column('door_qty', sa.Float(), nullable=True))
    op.add_column('co_schedules', sa.Column('frame_qty', sa.Float(), nullable=True))
    op.add_column('co_schedules', sa.Column('door_material_id', sa.String(length=36), nullable=True))
    op.add_column('co_schedules', sa.Column('door_material_code', sa.String(length=100), nullable=True))
    op.add_column('co_schedules', sa.Column('frame_material_id', sa.String(length=36), nullable=True))
    op.add_column('co_schedules', sa.Column('frame_material_code', sa.String(length=100), nullable=True))
    op.add_column('co_schedules', sa.Column('extra_attributes', sa.JSON(), nullable=True))
    op.add_column('co_schedules', sa.Column('door_type', sa.String(length=100), nullable=True))
    op.add_column('co_schedules', sa.Column('swing', sa.String(length=100), nullable=True))
    op.add_column('co_schedules', sa.Column('schedule_data', sa.JSON(), nullable=True))
    op.add_column('co_schedules', sa.Column('schedule_hardware_data', sa.JSON(), nullable=True))
    op.add_column('co_schedules', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('co_schedules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_schedules', 'created_at')
    op.drop_column('co_schedules', 'created_by')
    op.drop_column('co_schedules', 'schedule_hardware_data')
    op.drop_column('co_schedules', 'schedule_data')
    op.drop_column('co_schedules', 'swing')
    op.drop_column('co_schedules', 'door_type')
    op.drop_column('co_schedules', 'extra_attributes')
    op.drop_column('co_schedules', 'frame_material_code')
    op.drop_column('co_schedules', 'frame_material_id')
    op.drop_column('co_schedules', 'door_material_code')
    op.drop_column('co_schedules', 'door_material_id')
    op.drop_column('co_schedules', 'frame_qty')
    op.drop_column('co_schedules', 'door_qty')
    op.drop_column('co_schedules', 'location_2')
    op.drop_column('co_schedules', 'from_to')
    op.drop_column('co_schedules', 'location_1')
    op.drop_column('co_schedules', 'area')
    # ### end Alembic commands ###
