"""Added change_order_docs and change_order_status_logs table

Revision ID: 7a558dfe6ddc
Revises: f94b6cb61e18
Create Date: 2025-09-04 17:21:45.857464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a558dfe6ddc'
down_revision: Union[str, None] = 'f94b6cb61e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_order', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('change_order', sa.Column('co_number', sa.String(length=255), nullable=True))
    op.add_column('change_order', sa.Column('version', sa.String(length=255), nullable=True))
    op.add_column('change_order', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('change_order', sa.Column('current_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED', name='changeorderstatusenum'), nullable=True))
    op.drop_column('change_order', 'title')
    op.drop_column('change_order', 'status')
    op.add_column('schedules', sa.Column('is_in_change_order', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'is_in_change_order')
    op.add_column('change_order', sa.Column('status', mysql.ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED'), nullable=True))
    op.add_column('change_order', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('change_order', 'current_status')
    op.drop_column('change_order', 'priority')
    op.drop_column('change_order', 'version')
    op.drop_column('change_order', 'co_number')
    op.drop_column('change_order', 'project_id')
    # ### end Alembic commands ###
