"""is_default field for adon field option

Revision ID: 7d12abfc6ade
Revises: 6271cdc4e3bf
Create Date: 2025-01-06 16:02:47.933664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d12abfc6ade'
down_revision: Union[str, None] = '6271cdc4e3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adon_opening_field_options', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adon_opening_field_options', 'is_default')
    # ### end Alembic commands ###
