"""disocund and surcherge details added to project raw material

Revision ID: 7f2dde4ca51b
Revises: a1a67748c090
Create Date: 2025-04-23 14:56:37.418988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2dde4ca51b'
down_revision: Union[str, None] = 'a1a67748c090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_raw_material_manufacturer_quotes', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_raw_material_manufacturer_quotes', 'expiry_date')
    # ### end Alembic commands ###
