"""added rename from 'required_da' to 'required_by_date'

Revision ID: 7f57e351381a
Revises: be6695848bc8
Create Date: 2025-03-25 19:38:23.114027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f57e351381a'
down_revision: Union[str, None] = 'be6695848bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('required_by_date', sa.Date(), nullable=True))
    op.drop_column('active_po', 'date_required')
    op.drop_column('active_po', 'purchase_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('purchase_order', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('active_po', sa.Column('date_required', sa.DATE(), nullable=True))
    op.drop_column('active_po', 'required_by_date')
    # ### end Alembic commands ###
