"""removing 'is_disabled' filed from adon_opening_fields table

Revision ID: 7f6b68e2fe67
Revises: dd2fe531b713
Create Date: 2025-01-13 15:37:31.340935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f6b68e2fe67'
down_revision: Union[str, None] = 'dd2fe531b713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adon_opening_fields', 'is_disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adon_opening_fields', sa.Column('is_disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
