"""quatity and value added to schedule data table

Revision ID: 8183a34af589
Revises: 12228b7bf12d
Create Date: 2024-12-12 23:29:11.729431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8183a34af589'
down_revision: Union[str, None] = '12228b7bf12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('value', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('quantity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'quantity')
    op.drop_column('schedule_data', 'value')
    # ### end Alembic commands ###
