"""shipping label file path related changes in order item table

Revision ID: 8260852fd666
Revises: fbe9c9785b96
Create Date: 2025-03-13 12:58:55.066937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8260852fd666'
down_revision: Union[str, None] = 'fbe9c9785b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('label_file_name', sa.String(length=255), nullable=True))
    op.add_column('ordered_items', sa.Column('label_file_path', sa.String(length=255), nullable=True))
    op.add_column('ordered_items', sa.Column('label_content_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'label_content_type')
    op.drop_column('ordered_items', 'label_file_path')
    op.drop_column('ordered_items', 'label_file_name')
    # ### end Alembic commands ###
