"""feature data json added to schedule_installation_mapping_component_data table

Revision ID: 848fe462ca2d
Revises: 1b3774c61799
Create Date: 2025-06-05 22:53:29.831289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848fe462ca2d'
down_revision: Union[str, None] = '1b3774c61799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_installation_mapping_component_data', sa.Column('base_feature', sa.JSON(), nullable=True))
    op.add_column('schedule_installation_mapping_component_data', sa.Column('adon_feature', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_installation_mapping_component_data', 'adon_feature')
    op.drop_column('schedule_installation_mapping_component_data', 'base_feature')
    # ### end Alembic commands ###
