"""opening hardware group related tables added and sort order added to adon fields table

Revision ID: 860e5bbf3e92
Revises: a302c6a87dce
Create Date: 2024-12-19 14:01:34.685788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860e5bbf3e92'
down_revision: Union[str, None] = 'a302c6a87dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_hardware_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('item_count', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('opening_hardware_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('short_code', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('base_feature', sa.JSON(), nullable=True),
    sa.Column('base_price', sa.JSON(), nullable=True),
    sa.Column('adon_feature', sa.JSON(), nullable=True),
    sa.Column('adon_price', sa.JSON(), nullable=True),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('discount_is_basic', sa.Boolean(), nullable=True),
    sa.Column('content_file_path', sa.Text(), nullable=True),
    sa.Column('content_file_name', sa.Text(), nullable=True),
    sa.Column('content_file_type', sa.String(length=36), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FLAT', 'MULTIPLIER', name='discount_type'), nullable=True),
    sa.Column('surcharge', sa.Float(), nullable=True),
    sa.Column('surcharge_type', sa.Enum('PERCENTAGE', 'FLAT', 'MULTIPLIER', name='surcharge_type'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('opening_hardware_group_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('opening_hardware_material_id', sa.String(length=36), nullable=True),
    sa.Column('opening_hardware_group_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['opening_hardware_group_id'], ['opening_hardware_groups.id'], ),
    sa.ForeignKeyConstraint(['opening_hardware_material_id'], ['opening_hardware_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('adon_opening_fields', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('schedule_data', sa.Column('opening_hardware_group_material_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'schedule_data', 'opening_hardware_group_materials', ['opening_hardware_group_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_data', type_='foreignkey')
    op.drop_column('schedule_data', 'opening_hardware_group_material_id')
    op.drop_column('adon_opening_fields', 'sort_order')
    op.drop_table('opening_hardware_group_materials')
    op.drop_table('opening_hardware_materials')
    op.drop_table('opening_hardware_groups')
    # ### end Alembic commands ###
