"""opening schedule rated chaneg in db model

Revision ID: 86c69c2170f1
Revises: 950f793d9fe6
Create Date: 2024-12-09 17:04:06.030733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c69c2170f1'
down_revision: Union[str, None] = '950f793d9fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opening_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('HARDWARE', 'OPENING', name='schedule_type'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('take_off_area_item_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('project_raw_material_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_raw_material_id'], ['project_raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('component', sa.Enum('HARDWARE', 'FRAME', 'DOOR', 'OTHER', name='component_type'), nullable=True),
    sa.Column('feature_code', sa.String(length=250), nullable=True),
    sa.Column('option_code', sa.String(length=250), nullable=True),
    sa.Column('adon_feature_code', sa.String(length=250), nullable=True),
    sa.Column('adon_option_code', sa.String(length=250), nullable=True),
    sa.Column('base_feature', sa.JSON(), nullable=True),
    sa.Column('base_price', sa.JSON(), nullable=True),
    sa.Column('adon_feature', sa.JSON(), nullable=True),
    sa.Column('adon_price', sa.JSON(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('surcharge', sa.Float(), nullable=True),
    sa.Column('adon_field_id', sa.String(length=36), nullable=True),
    sa.Column('adon_field_option_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adon_field_id'], ['adon_opening_fields.id'], ),
    sa.ForeignKeyConstraint(['adon_field_option_id'], ['adon_opening_field_options.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_data')
    op.drop_table('schedules')
    # ### end Alembic commands ###
