"""changes in openinf_change_stats

Revision ID: 8a3dc8139db5
Revises: f3b5b785d0ad
Create Date: 2025-04-23 12:41:56.744779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a3dc8139db5'
down_revision: Union[str, None] = 'f3b5b785d0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opening_change_stats', sa.Column('take_off_discount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_discount', sa.Float(), nullable=True))
    op.drop_column('opening_change_stats', 'schedule_discount_percentage')
    op.drop_column('opening_change_stats', 'take_off_discount_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opening_change_stats', sa.Column('take_off_discount_percentage', mysql.FLOAT(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_discount_percentage', mysql.FLOAT(), nullable=True))
    op.drop_column('opening_change_stats', 'schedule_discount')
    op.drop_column('opening_change_stats', 'take_off_discount')
    # ### end Alembic commands ###
