"""Added the schedule_installation_mapping_activity and schedule_installation_mapping_attachment models

Revision ID: 8adaa80ea15f
Revises: 848fe462ca2d
Create Date: 2025-06-12 13:29:48.522409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adaa80ea15f'
down_revision: Union[str, None] = '848fe462ca2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_installation_mapping_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_installation_mapping_id', sa.String(length=36), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_id'], ['schedule_installation_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule_installation_mapping_attachment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_installation_mapping_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_installation_mapping_comment_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_comment_id'], ['schedule_installation_mapping_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_id'], ['schedule_installation_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_installation_mapping_attachment')
    op.drop_table('schedule_installation_mapping_activity')
    # ### end Alembic commands ###
