"""add installation mapping models

Revision ID: 936d3ba53056
Revises: 1bbb508bc019
Create Date: 2025-05-30 11:15:00.255954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936d3ba53056'
down_revision: Union[str, None] = '1bbb508bc019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_installation_plan_docs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('area', sa.String(length=250), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=250), nullable=True),
    sa.Column('content_type', sa.String(length=250), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule_installation_mapping',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_installation_plan_doc_id', sa.String(length=36), nullable=True),
    sa.Column('coordinate_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FAILED', 'SUCCESS', name='status'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['schedule_installation_plan_doc_id'], ['project_installation_plan_docs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule_installation_mapping_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_installation_mapping_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_id'], ['schedule_installation_mapping.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule_installation_mapping_prep_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_installation_mapping_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_data_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FAILED', 'SUCCESS', name='status'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_data_id'], ['schedule_data.id'], ),
    sa.ForeignKeyConstraint(['schedule_installation_mapping_id'], ['schedule_installation_mapping.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_installation_mapping_prep_data')
    op.drop_table('schedule_installation_mapping_comments')
    op.drop_table('schedule_installation_mapping')
    op.drop_table('project_installation_plan_docs')
    # ### end Alembic commands ###
