"""opening schedule rated chaneg in db model

Revision ID: 950f793d9fe6
Revises: ff5f238e078c
Create Date: 2024-12-09 16:56:28.920208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950f793d9fe6'
down_revision: Union[str, None] = 'ff5f238e078c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adon_opening_fields', sa.Column('has_price_dependancy', sa.Boolean(), nullable=True))
    op.add_column('adon_opening_fields', sa.Column('field_type', sa.Enum('NUMBER', 'TEXT', 'DROPDOWN', 'FILE_UPLOAD', name='addon_opening_field_type'), nullable=True))
    op.add_column('adon_opening_fields', sa.Column('field_category', sa.Text(), nullable=True))
    op.add_column('adon_opening_fields', sa.Column('is_door_data', sa.Boolean(), nullable=True))
    op.add_column('adon_opening_fields', sa.Column('is_frame_data', sa.Boolean(), nullable=True))
    op.add_column('adon_opening_fields', sa.Column('is_hw_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adon_opening_fields', 'is_hw_data')
    op.drop_column('adon_opening_fields', 'is_frame_data')
    op.drop_column('adon_opening_fields', 'is_door_data')
    op.drop_column('adon_opening_fields', 'field_category')
    op.drop_column('adon_opening_fields', 'field_type')
    op.drop_column('adon_opening_fields', 'has_price_dependancy')
    # ### end Alembic commands ###
