"""Added project_id in work_order table

Revision ID: 9f40fc9b23cd
Revises: 3fc4be99841d
Create Date: 2025-07-15 18:33:55.065079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f40fc9b23cd'
down_revision: Union[str, None] = '3fc4be99841d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('project_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order', 'project_id')
    # ### end Alembic commands ###
