"""project rawmaterial added with disc type and percentage and surcharge

Revision ID: a1a67748c090
Revises: d3b833535eec
Create Date: 2025-04-23 12:20:25.020888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a67748c090'
down_revision: Union[str, None] = 'd3b833535eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_raw_materials', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('project_raw_materials', sa.Column('surcharge_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_raw_materials', 'surcharge_amount')
    op.drop_column('project_raw_materials', 'discount_amount')
    # ### end Alembic commands ###
