"""added is_received and is_shipped flag in the active po table

Revision ID: a1ee41c9bc51
Revises: 3590b7e52ddf
Create Date: 2025-03-12 13:32:23.067616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ee41c9bc51'
down_revision: Union[str, None] = '3590b7e52ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_po', sa.Column('is_received', sa.Boolean(), nullable=True))
    op.add_column('active_po', sa.Column('is_shipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_po', 'is_shipped')
    op.drop_column('active_po', 'is_received')
    # ### end Alembic commands ###
