"""upload field added under schedule table

Revision ID: a302c6a87dce
Revises: 1d0a80113120
Create Date: 2024-12-18 16:03:58.112341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a302c6a87dce'
down_revision: Union[str, None] = '1d0a80113120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('frame_section_file_path', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('frame_section_file_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'frame_section_file_type')
    op.drop_column('schedules', 'frame_section_file_path')
    # ### end Alembic commands ###
