"""Added opening_number field in co_schedules table

Revision ID: a344396cb0ec
Revises: 5c3584a16a02
Create Date: 2025-09-08 16:13:15.377328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a344396cb0ec'
down_revision: Union[str, None] = '5c3584a16a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_schedules', sa.Column('opening_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_schedules', 'opening_number')
    # ### end Alembic commands ###
