"""adding different price breakups on opening change stats table

Revision ID: a75e171bc489
Revises: 6551d9d00d9c
Create Date: 2025-05-07 22:50:59.807798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75e171bc489'
down_revision: Union[str, None] = '6551d9d00d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opening_change_stats', sa.Column('short_code', sa.String(length=250), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_total_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_total_extended_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_final_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_final_extended_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_discount_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='discount_type'), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_surcharge', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_surcharge_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='surcharge_type'), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_margin', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('take_off_markup', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_total_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_total_extended_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_final_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_final_extended_sell_amount', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_discount_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='discount_type'), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_surcharge', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_surcharge_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='surcharge_type'), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_margin', sa.Float(), nullable=True))
    op.add_column('opening_change_stats', sa.Column('schedule_markup', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opening_change_stats', 'schedule_markup')
    op.drop_column('opening_change_stats', 'schedule_margin')
    op.drop_column('opening_change_stats', 'schedule_surcharge_type')
    op.drop_column('opening_change_stats', 'schedule_surcharge')
    op.drop_column('opening_change_stats', 'schedule_discount_type')
    op.drop_column('opening_change_stats', 'schedule_final_extended_sell_amount')
    op.drop_column('opening_change_stats', 'schedule_final_sell_amount')
    op.drop_column('opening_change_stats', 'schedule_total_extended_sell_amount')
    op.drop_column('opening_change_stats', 'schedule_total_sell_amount')
    op.drop_column('opening_change_stats', 'take_off_markup')
    op.drop_column('opening_change_stats', 'take_off_margin')
    op.drop_column('opening_change_stats', 'take_off_surcharge_type')
    op.drop_column('opening_change_stats', 'take_off_surcharge')
    op.drop_column('opening_change_stats', 'take_off_discount_type')
    op.drop_column('opening_change_stats', 'take_off_final_extended_sell_amount')
    op.drop_column('opening_change_stats', 'take_off_final_sell_amount')
    op.drop_column('opening_change_stats', 'take_off_total_extended_sell_amount')
    op.drop_column('opening_change_stats', 'take_off_total_sell_amount')
    op.drop_column('opening_change_stats', 'short_code')
    # ### end Alembic commands ###
