"""added take_off_data

Revision ID: aa7844fe24c6
Revises: 6235deca8f12
Create Date: 2025-04-20 05:21:10.058440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7844fe24c6'
down_revision: Union[str, None] = '6235deca8f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('take_off_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'take_off_data')
    # ### end Alembic commands ###
