"""shipping crate no related changes in order item table

Revision ID: adec10f7dbe4
Revises: 8260852fd666
Create Date: 2025-03-13 13:37:34.604555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adec10f7dbe4'
down_revision: Union[str, None] = '8260852fd666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('crate_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'crate_number')
    # ### end Alembic commands ###
