"""adding is_estimation in project_task table

Revision ID: aef6f11cf330
Revises: 7f2dde4ca51b
Create Date: 2025-04-24 00:02:33.190694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef6f11cf330'
down_revision: Union[str, None] = '7f2dde4ca51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_task', sa.Column('is_estimation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_task', 'is_estimation')
    # ### end Alembic commands ###
