"""schedule opening hw materials table name fix

Revision ID: b128022a4d30
Revises: 5f1443c9448f
Create Date: 2024-12-26 17:59:59.381657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b128022a4d30'
down_revision: Union[str, None] = '5f1443c9448f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_opening_hardware_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('opening_hardware_material_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['opening_hardware_material_id'], ['opening_hardware_materials.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('id', table_name='opening_hardware_group_materials')
    op.drop_table('opening_hardware_group_materials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_hardware_group_materials',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_base_amount', mysql.FLOAT(), nullable=True),
    sa.Column('total_extended_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('final_amount', mysql.FLOAT(), nullable=True),
    sa.Column('final_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('final_base_amount', mysql.FLOAT(), nullable=True),
    sa.Column('final_extended_sell_amount', mysql.FLOAT(), nullable=True),
    sa.Column('opening_hardware_material_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('schedule_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['opening_hardware_material_id'], ['opening_hardware_materials.id'], name='opening_hardware_group_materials_ibfk_1'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='opening_hardware_group_materials_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'opening_hardware_group_materials', ['id'], unique=True)
    op.drop_table('schedule_opening_hardware_materials')
    # ### end Alembic commands ###
