"""add on delete cascade in schedule_installation_mapping_comments and schedule_installation_mapping_prep_data

Revision ID: b86ea17973e0
Revises: 936d3ba53056
Create Date: 2025-05-30 16:21:08.392513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86ea17973e0'
down_revision: Union[str, None] = '936d3ba53056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_installation_mapping_comments_ibfk_1', 'schedule_installation_mapping_comments', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_installation_mapping_comments', 'schedule_installation_mapping', ['schedule_installation_mapping_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('schedule_installation_mapping_prep_data_ibfk_2', 'schedule_installation_mapping_prep_data', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_installation_mapping_prep_data', 'schedule_installation_mapping', ['schedule_installation_mapping_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_installation_mapping_prep_data', type_='foreignkey')
    op.create_foreign_key('schedule_installation_mapping_prep_data_ibfk_2', 'schedule_installation_mapping_prep_data', 'schedule_installation_mapping', ['schedule_installation_mapping_id'], ['id'])
    op.drop_constraint(None, 'schedule_installation_mapping_comments', type_='foreignkey')
    op.create_foreign_key('schedule_installation_mapping_comments_ibfk_1', 'schedule_installation_mapping_comments', 'schedule_installation_mapping', ['schedule_installation_mapping_id'], ['id'])
    # ### end Alembic commands ###
