"""added shipping status field in the ordered items table

Revision ID: b9d45571c1f3
Revises: a1ee41c9bc51
Create Date: 2025-03-12 18:13:30.303538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d45571c1f3'
down_revision: Union[str, None] = 'a1ee41c9bc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('shipping_status', sa.Enum('PENDING', 'IN_PROGRESS', 'AWAIT_SHIPPING', 'DONE', name='shipping_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'shipping_status')
    # ### end Alembic commands ###
