"""Added client_id in work_order table

Revision ID: bc63c0b85011
Revises: 9f40fc9b23cd
Create Date: 2025-07-16 18:54:26.152181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc63c0b85011'
down_revision: Union[str, None] = '9f40fc9b23cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('client_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order', 'client_id')
    # ### end Alembic commands ###
