"""assign hardware to opening schedule opening related changes 1

Revision ID: bf950fb381ef
Revises: 066d7840d6c0
Create Date: 2024-12-26 13:33:33.213982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf950fb381ef'
down_revision: Union[str, None] = '066d7840d6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_hardware_group_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_sell_amount', sa.Float(), nullable=True),
    sa.Column('total_base_amount', sa.Float(), nullable=True),
    sa.Column('total_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('final_sell_amount', sa.Float(), nullable=True),
    sa.Column('final_base_amount', sa.Float(), nullable=True),
    sa.Column('final_extended_sell_amount', sa.Float(), nullable=True),
    sa.Column('opening_hardware_material_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['opening_hardware_material_id'], ['opening_hardware_materials.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opening_hardware_group_materials')
    # ### end Alembic commands ###
