"""Added the opening_number with default none in co_schedules table

Revision ID: c2df2ec77d82
Revises: a344396cb0ec
Create Date: 2025-09-08 16:15:23.618660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2df2ec77d82'
down_revision: Union[str, None] = 'a344396cb0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
