"""new filed added to scheduled data

Revision ID: c56e4abd2bdb
Revises: b128022a4d30
Create Date: 2024-12-26 23:26:12.956145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56e4abd2bdb'
down_revision: Union[str, None] = 'b128022a4d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('is_adon_field', sa.Boolean(), nullable=True))
    op.add_column('schedule_data', sa.Column('has_price_dependancy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_data', 'has_price_dependancy')
    op.drop_column('schedule_data', 'is_adon_field')
    # ### end Alembic commands ###
