"""add material_description

Revision ID: cdc357027351
Revises: a7486eabba01
Create Date: 2026-04-09 13:05:22.364462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc357027351'
down_revision: Union[str, None] = 'a7486eabba01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_description',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_type', sa.String(length=36), nullable=False),
    sa.Column('raw_material_type', sa.String(length=100), nullable=False),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('base_feature', sa.JSON(), nullable=True),
    sa.Column('adon_feature', sa.JSON(), nullable=True),
    sa.Column('adon_fields', sa.JSON(), nullable=True),
    sa.Column('combination_key', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_material_description_combination_key'), 'material_description', ['combination_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_description_combination_key'), table_name='material_description')
    op.drop_table('material_description')
    # ### end Alembic commands ###
