"""adding new enu value completed to status field of change_order table

Revision ID: cedd13b6923d
Revises: 385c67b1d72e
Create Date: 2025-09-17 22:57:43.218056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cedd13b6923d'
down_revision: Union[str, None] = '385c67b1d72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_order', 'current_status',
               existing_type=mysql.ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED'),
               type_=sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='changeorderstatusenum'),
               existing_nullable=True)
    op.alter_column('change_order_status_logs', 'status',
               existing_type=mysql.ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED'),
               type_=sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='changeorderstatusenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_order_status_logs', 'status',
               existing_type=sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='changeorderstatusenum'),
               type_=mysql.ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED'),
               existing_nullable=True)
    op.alter_column('change_order', 'current_status',
               existing_type=sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='changeorderstatusenum'),
               type_=mysql.ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED'),
               existing_nullable=True)
    # ### end Alembic commands ###
