"""prepaid_collect_code_id convert to str

Revision ID: d01847732524
Revises: edefc166e7fb
Create Date: 2025-03-18 21:18:55.161026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd01847732524'
down_revision: Union[str, None] = 'edefc166e7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_po', 'prepaid_collect_code_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_po', 'prepaid_collect_code_id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
