"""adding new fileds in scehdule data table for latest data trach

Revision ID: d1c67093f314
Revises: cedd13b6923d
Create Date: 2025-09-17 23:36:27.377488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c67093f314'
down_revision: Union[str, None] = 'cedd13b6923d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('version', sa.String(length=250), nullable=True))
    op.add_column('schedule_data', sa.Column('latest_data', sa.Boolean(), nullable=True))
    op.add_column('schedule_data', sa.Column('has_ordered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    # Set default values for old records
    op.execute("UPDATE schedule_data SET latest_data = TRUE, has_ordered = FALSE, version = 'v0' WHERE latest_data IS NULL AND has_ordered IS NULL AND version IS NULL;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_data', 'has_ordered')
    op.drop_column('schedule_data', 'latest_data')
    op.drop_column('schedule_data', 'version')
    # ### end Alembic commands ###
