"""rawmaterial id added to schedule table and discount type added to schedule data

Revision ID: d3b833535eec
Revises: 2743e9e26830
Create Date: 2025-04-23 11:30:09.616402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b833535eec'
down_revision: Union[str, None] = '2743e9e26830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('discount_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='discount_type'), nullable=True))
    op.add_column('schedule_data', sa.Column('surcharge_type', sa.Enum('PERCENTAGE', 'MULTIPLIER', name='surcharge_type'), nullable=True))
    op.add_column('schedules', sa.Column('door_material_id', sa.String(length=100), nullable=True))
    op.add_column('schedules', sa.Column('frame_material_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'frame_material_id')
    op.drop_column('schedules', 'door_material_id')
    op.drop_column('schedule_data', 'surcharge_type')
    op.drop_column('schedule_data', 'discount_type')
    # ### end Alembic commands ###
