"""adding is basic discunt flag added to schedule data

Revision ID: d5961b497893
Revises: a75e171bc489
Create Date: 2025-05-08 16:24:53.498122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5961b497893'
down_revision: Union[str, None] = 'a75e171bc489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('is_basic_discount', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_data', 'is_basic_discount')
    # ### end Alembic commands ###
