"""added 'part_number' filed in the schedule_data api

Revision ID: dd2fe531b713
Revises: 025606873a01
Create Date: 2025-01-13 14:04:56.673093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2fe531b713'
down_revision: Union[str, None] = '025606873a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('part_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_data', 'part_number')
    # ### end Alembic commands ###
