"""adding shippent done flag fields to schedue_opening_hardware_material table

Revision ID: e4206057f397
Revises: 4ceeef349502
Create Date: 2025-09-23 11:34:35.135619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4206057f397'
down_revision: Union[str, None] = '4ceeef349502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_opening_hardware_materials', sa.Column('has_shipped', sa.Boolean(), nullable=True))
    op.execute("UPDATE schedule_opening_hardware_materials SET has_shipped = FALSE WHERE has_shipped IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_opening_hardware_materials', 'has_shipped')
    # ### end Alembic commands ###
