"""removed in_progress status from schedule_installation_mapping_component_data table

Revision ID: eb0ed4719cfd
Revises: 8adaa80ea15f
Create Date: 2025-06-13 12:13:54.189020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0ed4719cfd'
down_revision: Union[str, None] = '8adaa80ea15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
