"""rename order_by_date, delivery_date

Revision ID: edefc166e7fb
Revises: fc2245818acc
Create Date: 2025-03-18 14:58:50.985234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edefc166e7fb'
down_revision: Union[str, None] = 'fc2245818acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('required_by_date', sa.Date(), nullable=True))
    op.add_column('ordered_items', sa.Column('estimated_delivery_date', sa.Date(), nullable=True))
    op.drop_column('ordered_items', 'delivary_date')
    op.drop_column('ordered_items', 'order_by_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('order_by_date', sa.DATE(), nullable=True))
    op.add_column('ordered_items', sa.Column('delivary_date', sa.DATE(), nullable=True))
    op.drop_column('ordered_items', 'estimated_delivery_date')
    op.drop_column('ordered_items', 'required_by_date')
    # ### end Alembic commands ###
