"""ordered_item table

Revision ID: edf4cf9622a0
Revises: 7f6b68e2fe67
Create Date: 2025-02-12 15:00:07.078090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf4cf9622a0'
down_revision: Union[str, None] = '7f6b68e2fe67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordered_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=100), nullable=True),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('project_number', sa.String(length=100), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('opening_number', sa.String(length=100), nullable=True),
    sa.Column('door_type', sa.String(length=100), nullable=True),
    sa.Column('hand', sa.String(length=100), nullable=True),
    sa.Column('door_mat', sa.String(length=100), nullable=True),
    sa.Column('frame_mat', sa.String(length=100), nullable=True),
    sa.Column('ordered_metadata', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_base_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('final_base_price', sa.Float(), nullable=True),
    sa.Column('component_type', sa.Enum('HARDWARE', 'FRAME', 'DOOR', 'OTHER', name='components'), nullable=True),
    sa.Column('order_by_date', sa.Date(), nullable=True),
    sa.Column('delivary_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered_items')
    # ### end Alembic commands ###
