"""schedule_data_id removed from opening_change_stats

Revision ID: f3b5b785d0ad
Revises: fa3e49f7aa0f
Create Date: 2025-04-23 12:39:16.107821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3b5b785d0ad'
down_revision: Union[str, None] = 'fa3e49f7aa0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('opening_change_stats_ibfk_1', 'opening_change_stats', type_='foreignkey')
    op.drop_column('opening_change_stats', 'schedule_data_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opening_change_stats', sa.Column('schedule_data_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('opening_change_stats_ibfk_1', 'opening_change_stats', 'schedule_data', ['schedule_data_id'], ['id'])
    # ### end Alembic commands ###
