"""added take_off_hardware_data field to schedule table

Revision ID: f44b2ff7e924
Revises: a2aab06a2f33
Create Date: 2025-04-24 02:44:16.853983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44b2ff7e924'
down_revision: Union[str, None] = 'a2aab06a2f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('take_off_hardware_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'take_off_hardware_data')
    # ### end Alembic commands ###
