"""adding has started flag to work order assignee table

Revision ID: f94b6cb61e18
Revises: 45894b37f03e
Create Date: 2025-08-06 23:00:33.980710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94b6cb61e18'
down_revision: Union[str, None] = '45894b37f03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wo_assignee', sa.Column('has_started_working', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wo_assignee', 'has_started_working')
    # ### end Alembic commands ###
