"""new table opening_change_stats

Revision ID: fa3e49f7aa0f
Revises: aa7844fe24c6
Create Date: 2025-04-21 13:59:42.513020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3e49f7aa0f'
down_revision: Union[str, None] = 'aa7844fe24c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_change_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_data_id', sa.String(length=36), nullable=True),
    sa.Column('opening_number', sa.String(length=100), nullable=True),
    sa.Column('component', sa.Enum('HARDWARE', 'FRAME', 'DOOR', 'OTHER', 'OPENING', name='component_type'), nullable=True),
    sa.Column('field_name', sa.String(length=250), nullable=True),
    sa.Column('take_off_feature_code', sa.String(length=250), nullable=True),
    sa.Column('schedule_feature_code', sa.String(length=250), nullable=True),
    sa.Column('take_off_option_code', sa.String(length=250), nullable=True),
    sa.Column('take_off_value', sa.String(length=250), nullable=True),
    sa.Column('schedule_option_code', sa.String(length=250), nullable=True),
    sa.Column('schedule_value', sa.String(length=250), nullable=True),
    sa.Column('take_off_total_amount', sa.Float(), nullable=True),
    sa.Column('take_off_total_base_amount', sa.Float(), nullable=True),
    sa.Column('take_off_quantity', sa.Float(), nullable=True),
    sa.Column('take_off_final_amount', sa.Float(), nullable=True),
    sa.Column('take_off_final_base_amount', sa.Float(), nullable=True),
    sa.Column('take_off_discount_percentage', sa.Float(), nullable=True),
    sa.Column('schedule_total_amount', sa.Float(), nullable=True),
    sa.Column('schedule_total_base_amount', sa.Float(), nullable=True),
    sa.Column('schedule_quantity', sa.Float(), nullable=True),
    sa.Column('schedule_final_amount', sa.Float(), nullable=True),
    sa.Column('schedule_final_base_amount', sa.Float(), nullable=True),
    sa.Column('schedule_discount_percentage', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('is_adon_field', sa.Boolean(), nullable=True),
    sa.Column('has_price_dependancy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['schedule_data_id'], ['schedule_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opening_change_stats')
    # ### end Alembic commands ###
