"""added created_at on ordered_item_docs table

Revision ID: fbe9c9785b96
Revises: 49ba7d1f7bc3
Create Date: 2025-03-12 20:43:45.513614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe9c9785b96'
down_revision: Union[str, None] = '49ba7d1f7bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_item_docs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_item_docs', 'created_at')
    # ### end Alembic commands ###
