"""added shipping_id, packing_info in the ordered_items table

Revision ID: fc2245818acc
Revises: adec10f7dbe4
Create Date: 2025-03-17 13:01:15.731500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2245818acc'
down_revision: Union[str, None] = 'adec10f7dbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_items', sa.Column('shipment_id', sa.String(length=50), nullable=True))
    op.add_column('ordered_items', sa.Column('packing_info', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_items', 'packing_info')
    op.drop_column('ordered_items', 'shipment_id')
    # ### end Alembic commands ###
