"""added is_estimation in project table

Revision ID: ff5f238e078c
Revises: 88876dffe341
Create Date: 2024-11-26 14:57:09.787043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5f238e078c'
down_revision: Union[str, None] = '88876dffe341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_estimation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_estimation')
    # ### end Alembic commands ###
